variables:
  # Docker Hub credentials
  dockerhub_connection: 'dockerhub_connection'
  dockerhub_repository: 'epureanudiana/app'

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      containerRegistry: $(dockerhub_connection)
      repository: $(dockerhub_repository)
      command: 'build'
      Dockerfile: app.Dockerfile
      buildContent: .
      tags: "latest"


  - task: Docker@2
    displayName: 'Push Docker image to Docker Hub'
    inputs:
      containerRegistry: $(dockerhub_connection)
      repository: $(dockerhub_repository)
      command: 'push'
      Dockerfile: app.Dockerfile
      tags: "latest"

  - script:


