# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# build docker image
# push docker image to docker hub


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: "Build"
    inputs:
      containerRegistry: "dockerhub_connection"
      repository: 'epureanudiana/app'
      Dockerfile: app.Dockerfile
      buildContent: .
      tags: "latest"

  - task: Docker@2
    displayName: "Push"
    inputs:
      containerRegistry: "dockerhub_connection"
      repository: 'epureanudiana/app'
      Dockerfile: app.Dockerfile
      command: "push"
      tags: "latest"

