variables:
  # Docker Hub credentials
  dockerhub_connection: 'dockerhub_connection'
  dockerhub_repository: 'epureanudiana/app'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Docker image'
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              containerRegistry: $(dockerhub_connection)
              repository: $(dockerhub_repository)
              command: 'build'
              Dockerfile: app.Dockerfile
              buildContent: .
              tags: "latest"

  - stage: Test
    dependsOn: Build
    displayName: 'Test Docker image'
    jobs:
      - job: Test
        displayName: 'Test'
        steps:
          - script: |
              # Run unit tests here
              echo 'Running unit tests...'
            displayName: 'Run unit tests'

  - stage: Test2
    dependsOn: Build
    displayName: 'Test Docker image'
    jobs:
      - job: Test
        displayName: 'Test'
        steps:
          - script: |
              # Run unit tests here
              echo 'Running unit tests...'
            displayName: 'Run unit tests'

  - stage: Deploy
    dependsOn:
      - Test
      - Test2
    displayName: 'Deploy Docker image'
    jobs:
      - job: Deploy
        displayName: 'Deploy'
        steps:
          - task: Docker@2
            displayName: 'Push Docker image to Docker Hub'
            inputs:
              containerRegistry: $(dockerhub_connection)
              repository: $(dockerhub_repository)
              command: 'push'
              Dockerfile: app.Dockerfile
              tags: "latest"
