variables:
  # Docker Hub credentials
  dockerhub_connection: 'dockerhub_connection'
  dockerhub_repository: 'epureanudiana/app'

trigger:
  - main



jobs:
  - job: build_push_on_linux
    displayName: "Build and Push on linux "
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Bash@3
        displayName: 'Build Docker image'
        inputs:
          targetType: 'inline'
          script: |
            echo 'Building Docker image...'
            sleep 2
            echo 'Docker image built!'

      - script: |
          echo 'Pushing Docker image to Docker Hub...'
          sleep 2
          echo 'Docker image pushed!'
        displayName: 'Push Docker image to Docker Hub'

  - job: build_push_on_mac
    displayName: "Build and Push on mac "
    pool:
      vmImage: 'macOS-latest'
    steps:
      - task: Bash@3
        displayName: 'Build Docker image'
        inputs:
          targetType: 'inline'
          script: |
            echo 'Building Docker image...'
            sleep 2
            echo 'Docker image built!'

      - script: |
          echo 'Pushing Docker image to Docker Hub...'
          sleep 2
          echo 'Docker image pushed!'
        displayName: 'Push Docker image to Docker Hub'


