trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Docker Hub credentials
  dockerRegistryServiceConnection: 'dockerhub_connection'
  imageRepository: 'app'
  containerRegistry: 'docker.io'

steps:
- script: |
    echo 'Starting the Docker build...'
    docker build --rm --tag $(imageRepository) .
  displayName: 'Docker Build'

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    command: 'push'
    tags: 'latest'