trigger:
- master


variables:
  # Docker Hub credentials
  dockerRegistryServiceConnection: 'dockerhub_connection'
  imageRepository: 'epureanudiana/app'
  dockerfileName: 'app.Dockerfile'

jobs:
  - job: "Ubuntu"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: 'Build Docker Image'
        inputs:
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageRepository)
          Dockerfile: app.Dockerfile
          buildContext: .
          tags: 'latest'

      - task: Docker@2
        displayName: 'Push Docker Image'
        inputs:
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageRepository)
          Dockerfile: $(dockerfileName)
          buildContext: .
          command: 'push'
          tags: 'latest'

      - task: Docker@2
        displayName: 'Run Docker Image'
        inputs:
          containerRegistry: $(dockerRegistryServiceConnection)
          repository: $(imageRepository)
          Dockerfile: $(dockerfileName)
          command: 'run'
          arguments: 'python submit_inference_job.py'