trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Docker Hub credentials
  dockerRegistryServiceConnection: 'dockerhub_connection'
  imageRepository: 'epureanudiana/app'
  containerRegistry: 'docker.io'

steps:
- task: CommandLine@2
  inputs:
    script: 'docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHUB_PASSWORD)'
    addSpnToEnvironment: true

- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    Dockerfile: app.Dockerfile
    buildContext: .
    tags: 'latest'

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    Dockerfile: app.Dockerfile
    buildContext: .
    command: 'push'
    tags: 'latest'