trigger: none

pr:
  branches:
    include:
    - main

parameters:
- name: SkipOSXTests
  displayName: "Skip tests on OSX"
  type: boolean
  default: false

variables:
  skipOSXTests: ${{ parameters.SkipOSXTests }}

stages :
  - stage: Tests
    displayName: 'Run pre-deployment tests'
    jobs:
      - job: OSX
        dependsOn:
        pool:
          vmImage: macOS-latest
        strategy:
          matrix:
            Python3.7:
              python.version: '3.7'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
            displayName: 'Use Python $(python.version)'

          - script: |
              source activate det2
              export MACOSX_DEPLOYMENT_TARGET=10.9
              CC=clang CXX=clang++ ARCHFLAGS="-arch x86_64" python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@v0.5'
            displayName: 'Create env and Install dependencies'

          - ${{ if eq(variables.skipOSXtests, 'true') }}:
            - script: |
                source activate det2
                pytest -s --cov=. --cov-report html --cov-report term-missing
              displayName: 'pytest'