variables:
  # Docker Hub credentials
  dockerhub_connection: 'dockerhub_connection'
  dockerhub_repository: 'epureanudiana/app'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - template: templates/docker-build.yml
    parameters:
      dockerhub_connection: $(dockerhub_connection)
      dockerhub_repository: $(dockerhub_repository)

  - stage: Test
    dependsOn: Build
    displayName: 'Test Docker image'
    jobs:
      - job: Test
        displayName: 'Test'
        steps:
          - script: |
              # Run unit tests here
              echo 'Running unit tests...'
            displayName: 'Run unit tests'

  - stage: Test2
    dependsOn: Build
    displayName: 'Test Docker image'
    jobs:
      - job: Test
        displayName: 'Test'
        steps:
          - script: |
              # Run unit tests here
              echo 'Running unit tests...'
            displayName: 'Run unit tests'

  - stage: Deploy
    dependsOn:
      - Test
      - Test2
    displayName: 'Run'
    jobs:
      - job: Pull
        displayName: 'Pull'
        steps:
          - task: Docker@2
            displayName: 'Pull Docker image from Docker Hub'
            inputs:
              containerRegistry: $(dockerhub_connection)
              repository: $(dockerhub_repository)
              command: 'pull'
              tags: "latest"
          - task: Docker@2
            displayName: 'Run Docker container'
            inputs:
              containerRegistry: $(dockerhub_connection)
              repository: $(dockerhub_repository)
              command: 'run'
              arguments: '-d -p 80:80 python submit_inference_script.py'
              tags: "latest"
