trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'


jobs:
  - job: Build
    displayName: 'Build'
    steps:
      - task: Bash@3
        displayName: 'Print Hello, World!'
        inputs:
          targetType: 'inline'
          script: 'echo "Hello, World!"'

      - script: echo Hello world!
        displayName: Say hello


